### ISSUE TITLE
Query string support

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/api-client#2]
Probably just use [qs](https://github.com/hapijs/qs) or something and let people pass in objects.

**Comment by bbesmanoff** [comment]
:+1: Default it to no params, allow users to override that.  Does the API document what operations support query strings?

**Comment by craigcabrey** [comment]
@bbesmanoff No operations are supported yet. What would we like to support?

* `with`: Include relations
* `filter`: General filtering? If so, what parameters?

**Comment by kristenmills** [comment]
I'm going to make a bunch of issues on API  after I eat. It will outline what i think we need for each endpoint and then we can discuss it in an organized fashion

**Comment by kristenmills** [comment]
query string support is added in #3. I'll close when that's merged.
