### ISSUE TITLE
Suggestion: Promises > Callbacks

### ISSUE THREAD

**Issue by weswigham** [rit-sse/api-client#4]
Because the enlightened among us using babel can then just use async/await.

**Comment by kristenmills** [comment]
It actually initially used promises, we stopped so that our public facing code is all es5 compliant. There was a whole discussion about it.

**Comment by weswigham** [comment]
Just use https://www.npmjs.com/package/promise ? I never said you had to use language promises.

**Comment by kristenmills** [comment]
You can also wrap the library yourself when you are using it. That's what I was planning to do in the future. If you're really lazy, bluebird will do it for you. I'm closing this issue because this is the decision that was made. Sorry Wesley.
