### ISSUE TITLE
Pagination support in the client

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/api-client#5]
For Example

```
Member.all().next().prev();
```

**Comment by bbesmanoff** [comment]
Would they be chainable like that?

What should happen for `prev()` on the first page and `next` on the last page (errors? current page?)

**Comment by kristenmills** [comment]
I'm hoping to have them chainable like that. But i have to figure out a non janky way to do it.  We'll see. 

I would say it would probably error in some fashion. Current page is just false information.

**Comment by vuzDylan** [comment]
Hmm I forgot about this this is a good idea. I got this shit (maybe next week).

**Comment by kristenmills** [comment]
I think I already did this?

**Comment by kristenmills** [comment]
Go look at the imagination-pagination branch...not sure what state that is in.

**Comment by vuzDylan** [comment]
@kristenmills check out the branch https://github.com/rit-sse/api-client/tree/pagination
